### ISSUE TITLE
"mono" not found

### ISSUE THREAD

**Issue by Vasilich** [oleg-shilo/cs-script.vscode#1]
Trying to use VSCode for csscript, but any command (debug, run, compile) outputs "Der Befehl "mono" ist entweder falsch geschrieben oder konnte nicht gefunden werden." (german, means "Command 'mono' is either wrong typed or cannot be found." / "Bad command or file name").
Any suggestion what can be wrong?
Using latest cs-script with latest VSCode (1.12.2) on german windows 7.

**Comment by oleg-shilo** [comment]
Hi, the extension relies on two other extensions: 
![image](https://cloud.githubusercontent.com/assets/16729806/26568839/efdecaa8-4549-11e7-901a-cb6b3a9ece4e.png)

In the previous release the dependencies were not expressed properly in the manifest file so you are probably missing Mono Debug extension and Mono itself. 

You can either install `Mono Debug` extension manually. Or get the very latest CS-Script.VSCode update (I just published it) and VSCode should pick the dependency and install `Mono Debug` automatically.

**Comment by Vasilich** [comment]
Mono Debug was already installed. I just updated csscript.vscode to latest version, but nothing changed - same error.
Yes, i don't have Mono explicitly installed - i thought it is the part VSCode itself? I just got used to use csscript without installing something additional. Should i install Mono for windows to use csscript under vscode?

**Comment by oleg-shilo** [comment]
My bad. I assumed that Mono came on my system with `Mono Debug` extension. I was wrong. It is an independent install. Please install Mono form the official Mono repo: http://www.mono-project.com/download. I just tested v5.0.1 from there it works. 

Keep in mind that the official latest Mono still doesn't support C# 7 but C# 6 only. I guess it will catch up soon.

**Comment by Vasilich** [comment]
After installing Mono and manuallz adding its path to global PATH environment variable, cs-script.vscode can be compiled. I still have some problems with debugging, because i selected once .NET Core debugger, but i will solve it later.
Is Mono a requirement for cs-script to be compiled/debugged in vscode? CSScript itself doesn't require it as it uses .NET available/installed in OS.

**Comment by oleg-shilo** [comment]
> Is Mono a requirement for cs-script to be compiled/debugged in vscode?

Yes. cs-script itself does not require mono on Win. This is how cs-script is hosted in Notepad++ in a pure Win manner:
```
Run: cscs.exe <script>
Debug: mdbg.exe cscs.exe <script>
```
And this how it's done under vscode:
```
Run: mono cscs.exe <script>
Debug: mono --debug --debugger-agent cscs.exe <script>
```
Of course if it is windows running can be done without mono but I feel that it is better to keep the same runtime for running and debugging. though I will allow customizing the launcher (e.g. dropping 'mono') but before that I need to collect some feedback. The extension is just two days old :)

> I still have some problems with debugging, because i selected once .NET Core debugger...

Yeas it might be a problem. I haven't use .NET Core debugger yet so my VSCode config is a default one. Though I am not entirely convinced how .NET Core debugger can interfere. On `cs-script.debug` (Alt+F5) the extension explicitly lunches mono: 
```TS
var editor = vscode.window.activeTextEditor;
let launchConfig = {
    "name": "Launch",
    "type": "mono",
    "request": "launch",
    "program": cscs_exe,
    "args": ["-nl", "-d", "-l", "-inmem:0", "-ac:2", "-config:none", editor.document.fileName]
};

vscode.commands.executeCommand('vscode.startDebug', launchConfig);
```

But who knows...

**Comment by Vasilich** [comment]
thank you Oleg, so far got everything working now.
