### ISSUE TITLE
Debugging in Mac m2 Pro does not work 

### ISSUE THREAD

**Issue by yao-big** [oleg-shilo/cs-script.vscode#38]
The vscode plugin CS Script Mono Debug C # has been installed 

Mono has also been installed 

<img width="241" alt="image" src="https://github.com/oleg-shilo/cs-script.vscode/assets/30170943/84679a82-f935-45ad-86b4-236d2fb36fd4">
<img width="752" alt="image" src="https://github.com/oleg-shilo/cs-script.vscode/assets/30170943/9e90734c-008d-40e9-8b50-7eac5e72c3e8">
The program can run normally, but clicking the debug button does not respond

Is it a problem with my local environment? Can you provide some guidance? Thank you very much

**Comment by yao-big** [comment]
I searched for a lot of information but couldn't solve this problem. What should I do?

**Comment by oleg-shilo** [comment]
I am not sure what cs-script version you are running. The plugin that is currently distributed is compiled against .NET but not .NET Framework. Thus it cannot be executed nor debugged unless you have .NET 8.0 installed. If you do, then you don't need mono at all.

You just have VSCode .NET tools installed and it's all you need

**Comment by yao-big** [comment]
The. net version is 8.0 cs script, which is the latest version

**Comment by oleg-shilo** [comment]
OK, then I do not know who the mono compiler is in the picture.

cs-script is executed under the hood with the `dotnet` executable, not Mono.

And for debugging VSCode is using the .NET tools plugin but not the Mono plugin.

This is the primary problem. 

The secondary problem is that I made a mistake in my answer. The VSCode CS-Script plugin depends on .NET 7 not .NET 8.
Thus unless you also install .NET7 SDK you will not be able to run/debug.
Thus I will urgently release the update so the plugin targets the latest .NET

I will prioritize this work, but it will not help you until you solve the Mono problem.

**Comment by oleg-shilo** [comment]
Mind you that there is also an option to configure an external deployment of CS-Script engine (e.g. via nuget) instead of the one that is distributed with the plugin:
![image](https://github.com/oleg-shilo/cs-script.vscode/assets/16729806/e97828c8-d91f-47c9-bab7-7c5ca6fa143e)
This can be used when you want to use a specific version of the engine.

**Comment by oleg-shilo** [comment]
Done, I just have published the update to the plugin that includes the cs-script version that targets .NET 8.0
![image](https://github.com/oleg-shilo/cs-script.vscode/assets/16729806/da826e11-c8ea-4879-a538-6f02517ecca3)
. . .
So after you update the plugin:
- Open a fresh **empty** instance of VSCode
- Create a new script:
  ![image](https://github.com/oleg-shilo/cs-script.vscode/assets/16729806/ab431d5a-34f6-400b-9ccf-80f98aeff00a)
- And now either execute the script:
  ![image](https://github.com/oleg-shilo/cs-script.vscode/assets/16729806/af60e23f-d920-4fcb-aa51-7a32e52c9eba)
  Or debug it:
  ![image](https://github.com/oleg-shilo/cs-script.vscode/assets/16729806/8964129e-2a7b-4c76-a34b-f316d5af7cb9)

**Comment by oleg-shilo** [comment]
And this is the result
![image](https://github.com/oleg-shilo/cs-script.vscode/assets/16729806/33f867eb-9d47-42d8-8424-586e832c9ce8)

**Comment by yao-big** [comment]
May I ask how to install CS script on Mac? I tried several methods, but none of them worked

**Comment by oleg-shilo** [comment]
Install .NET SDK 8.
Then install the script engine by any of the installation approaches from the release notes. See the deployment section: https://github.com/oleg-shilo/cs-script/releases/tag/v4.8.16.0

In your case it will be either manual approach or as a .net tool. I suggest you do the second:
```
dotnet tool install --global cs-script.cli
``` 
Now you can execute cs-script as 
```
dotnet <path to cscs.dll> --version
```
I would recommend creating an alias:
```
alias css='dotnet /usr/local/bin/cs-script/cscs.dll'+
. . .
css --version
```

After that you can create the script
```
css -new test.cs
```

and execute it

```
css test.cs
```

**Comment by yao-big** [comment]
CS script has been installed and still cannot be used

I recorded a video, you can take a look

Operating system Mac m2

Vscode version 1.90.2

CS script latest v

https://github.com/oleg-shilo/cs-script.vscode/assets/30170943/f51f5d7e-0ba6-4abe-b31e-3b298bd9f5d1

ersion

**Comment by yao-big** [comment]
<img width="1649" alt="image" src="https://github.com/oleg-shilo/cs-script.vscode/assets/30170943/4ceff3f0-27fb-4394-ad7f-95793a022199">

**Comment by oleg-shilo** [comment]
Great progress.
CS-Script works now perfectly.

The only thing that is not happening for you is debugging. 

I have checked and in `debug()` routine found some dead code that is not executed but... I do not like that it hangs there and potentially interferes with the debugging. I cannot check it as I do not have mac environment. So I just removed the dead code and published a pre-release for you: https://github.com/oleg-shilo/cs-script.vscode/releases/tag/v2.2.3-pre

So please check if it helps. Remember, you must ensure you have no workspace/folder open in VSCode. Only a single cs file.

The whole debugging is not a rocket science. Plugin simply executes `vscode.debug.startDebugging(undefined, launchConfig)` where launchConfig is a `launch.json` that I distribute with the plugin. 

I captured this file from a sample C# project I created with VSCode.

Maybe this `launchConfig` is somehow invalid in your environment. On Linux it's fine... 

```TS
let launchConfig = {
            name: ".NET Core Launch (console)",
            type: "coreclr",
            request: "launch",
            program: "dotnet",
            args: [settings.cscs, "-d", extra_args().replace("-co:/debug:pdbonly", ""), vsc_config.get("cs-script.extra_args"), "", "-l", "-ac:2", editor.document.fileName],
            cwd: path.dirname(editor.document.fileName),
            console: "internalConsole",
            stopAtEntry: false
        }
```

**Comment by yao-big** [comment]
I found that there must be no open workspace/folder in VSCode. Is it normal for only one CS file to be debugged?

**Comment by oleg-shilo** [comment]
Yes, it is normal. In fact, it is the only right way for the extension to operate. Otherwise, if you start debugging the script while VSCode has the workspace it is not clear what is going to be debugged an open document or an open folder.


This is the reason I have asked you to open VSCode without any folder loaded. I even used work empty in bold. :)

![image](https://github.com/oleg-shilo/cs-script.vscode/assets/16729806/fafb318c-3f46-4b45-b7a9-3bb46519de2a)

**Comment by yao-big** [comment]
Okay, thank you. It's already troublesome and you can now use it normally. This is a great feature

**Comment by yao-big** [comment]
Sure, thank you very much. It's already working fine now. This is a great feature, and I'm very grateful for your help.
